APP_NAME = "hypervolt-agile-scheduler"
LOG_LEVEL = "INFO"
FILE_LOG_LEVEL = "INFO"
LOG_MAX_BYTES = 10 * 1024 * 1024
ELECTRICITY_VAT_RATE = 1.05
SESSION_CLOCK_OFFSET_MINS = 1
TIMEZONE = "Europe/London"
