services:
  hypervolt-agile-scheduler:
    container_name: hypervolt-agile-scheduler
    image: mholubinka1/hypervolt-agile:latest
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./config:/config
      - ./log:/logs
      - ./extensions:/extensions
    restart: unless-stopped
