services:
  hypervolt-agile-scheduler:
    container_name: hypervolt-agile-scheduler
    image: mholubinka1/hypervolt-agile:latest
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /mnt/media/pi-media/containers/hypervolt-agile-scheduler/config:/config
      - /mnt/media/pi-media/containers/hypervolt-agile-scheduler/log:/logs
      - /mnt/media/pi-media/containers/hypervolt-agile-scheduler/extensions:/extensions
    restart: unless-stopped
